language: node_js
node_js:
  - "8.2.1"
before_script:
  - "npm install -g npm@5.3.0"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script: ./build.sh