version: 0.0.{build}
image: Visual Studio 2017
init:
  - git config --global core.autocrlf true
  - npm install -g npm@5.3.0
install:
  - ps: Install-Product node 8.1.4
build_script:
  - cmd: build.cmd
test: off
artifacts:
- path: build/dist
  name: BuildResult