version: 0.0.{build}
image: Visual Studio 2017
init:
  - git config --global core.autocrlf true
install:
  - ps: Install-Product node 6.10.3
build_script:
  - cmd: build.cmd
test: off
artifacts:
- path: build/dist
  name: BuildResult